# Generated by Django 3.0.3 on 2020-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Lawyer', 'Lawyer'), ('Witness', 'Witness'), ('Plaintiff', 'Plaintiff')], max_length=255),
        ),
    ]
