# Generated by Django 3.0.3 on 2020-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('postphoned', 'PostPhoned'), ('closed', 'Closed')], default='p', max_length=100),
        ),
    ]
